name: AI Code Review

on:
  push:
    paths:
      - 'TR_Sanity_TaxCaddy/**/*.xaml'
  pull_request:
    paths:
      - 'TR_Sanity_TaxCaddy/**/*.xaml'

jobs:
  review:
    runs-on: self-hosted
    env:
      EXTRACT_PATH: D:/wrk
    steps:
      - name: Setup 7-Zip
        shell: pwsh
        run: |
          $7zipUrl = "https://www.7-zip.org/a/7z2301-x64.exe"
          $7zipInstaller = "$env:TEMP\7z2301-x64.exe"
          Invoke-WebRequest -Uri $7zipUrl -OutFile $7zipInstaller
          Start-Process -FilePath $7zipInstaller -Args "/S" -Wait
          $env:PATH = "C:\Program Files\7-Zip;$env:PATH"

      - name: Configure Git
        run: |
          git config --system core.longpaths true
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            TR_Sanity_TaxCaddy
            src
            config

      - name: Extract if needed
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          try {
            if (Test-Path "${{ github.workspace }}/*.tar.gz") {
              $extractPath = "D:/wrk"
              Write-Host "Creating extraction directory at $extractPath"
              New-Item -ItemType Directory -Path $extractPath -Force
              
              Write-Host "Enabling long path support"
              Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Type DWord
              
              Write-Host "Extracting archive..."
              & "C:\Program Files\7-Zip\7z.exe" x "${{ github.workspace }}/*.tar.gz" -o"$extractPath" -y
              if ($LASTEXITCODE -ne 0) { throw "7-Zip extraction failed" }
              
              Write-Host "Moving extracted files..."
              Get-ChildItem $extractPath | Move-Item -Destination ${{ github.workspace }} -Force
            }
          }
          catch {
            Write-Error "Extraction failed: $_"
            throw
          }

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Set environment variables
        env:
          AI_ARENA_API_KEY: ${{ secrets.AI_ARENA_API_KEY }}
          AI_ARENA_ENDPOINT: ${{ secrets.AI_ARENA_ENDPOINT }}
        run: echo "Environment variables set"

      - name: Run AI code review
        run: python src/main.py

      - name: Upload AI code review reports
        uses: actions/upload-artifact@v4
        with:
          name: ai-code-review-reports
          path: |
            src/AI Reports/*.html
            src/AI Reports/*.json
